version: '3.6'

services:
  akhq:
    container_name: akhq-mai
    image: tchiotludo/akhq:0.24.0
    ports:
      - 9090:8080
    volumes:
      - ./application.yml:/app/application.yml
      - ./keystore_reg.pfx:/app/keystore_reg.pfx

